### 自定义层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn 

不带参数的层

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, Y):
        return Y - Y.mean()

In [4]:
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,45,3]))

tensor([-9.8000, -8.8000, -7.8000, 34.2000, -7.8000])

In [7]:
net = nn.Sequential(nn.Linear(6, 128), layer)
Y = net(torch.randn(3,6))
Y.sum()

tensor(2.6226e-06, grad_fn=<SumBackward0>)

带参数的层

In [8]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = torch.randn(in_units, units)
        self.bias = torch.randn(units)
    def forward(self, X):
        linear = torch.matmul(X, self.weight) + self.bias
        return F.relu(linear) 
        

In [9]:
linear = MyLinear(5,3)
linear.weight

tensor([[ 0.1356,  1.5884, -1.3076],
        [ 0.3588, -0.0285, -0.7663],
        [-0.7685, -0.1405,  0.7614],
        [ 0.7127, -0.0929,  0.1339],
        [ 0.1547, -1.8781,  0.2164]])

In [10]:
linear(torch.rand(2,5))

tensor([[2.1251, 1.4462, 0.0000],
        [1.8572, 2.9864, 0.0000]])

In [11]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(3, 64))

tensor([[7.3976],
        [5.4151],
        [6.8050]])

设计一个接受输入并计算张量降维的层torch.squeeze（）

In [39]:
class Squee(nn.Module):
    def __init__(self, W):
        super().__init__()
        self.wi = W.shape[0]
        self.Wj = W.shape[1]
        self.Wk = W.shape[2]
        self.W = W
    def forward(self, X):
        y = torch.randn(self.Wk,1)
        for i in range(self.Wk):
            y[i] = torch.sum(torch.mul(torch.matmul(X, X.T), self.W[:, :, i]))
        return y

In [41]:
W = torch.randn(size=(3,3,3))
sq = Squee(W)
X = torch.randn(3,1)
sq(X)

tensor([[-0.8416],
        [-0.2401],
        [ 0.5914]])